title: Jason'Log
description: everything should be made as simple as possible, but not simpler
theme: just-the-docs

url: https://Jason-cs18.github.io/ml-engineering

favicon_ico: "/assets/images/favicon.ico"

math: katex

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

compress_html:
  blanklines: true

aux_links:
  Template Repository: https://github.com/Jason-cs18/ml-engineering
