title: ML Engineering Blogs
description: everything should be made as simple as possible, but not simpler
theme: just-the-docs

url: https://Jason-cs18.github.io/ml-engineering

aux_links:
  Template Repository: https://github.com/Jason-cs18/ml-engineering
